# Description for social sharing and search engines.
description = "A collection of R packages for modeling and machine learning using tidyverse principles."

# Default image for social sharing and search engines. Place image in `static/images/` folder and specify image name here.
sharing_image = "feature_summary_large_image.jpg"
twitter_image = "feature_summary_large_image.jpg"

# Link custom CSS and JS assets
#   (relative to /static/css and /static/js respectively)
custom_css = ["tm.css"]
custom_js = ["tm.js"]

# Define base hex url for index page (where the stickers link out to)
hex_base_url = ".tidymodels.org/"
hex_ext = "svg"
    
# Define "news" as both articles and events
mainSections = ["articles", "events"]

# options for highlight.js (version, additional languages, and theme)
disable_highlightjs = "true"
highlightjsVersion = "9.11.0"
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"

MathJaxCDN = "//cdn.bootcss.com"
MathJaxVersion = "2.7.1"

[footer]
    github_url = ""
    twitter_url = ""
    support = "Proudly supported by"

# leave blank in quotes for the default = true
# to turn off, set = false (no quotes)
[authors]
    show_list = "" # on list page, default is true
    show_single = "" # on single pages, default is true
    show_latest = "" # on bio, default is true
    label_latest = "" # on bio, default is "Latest"

# leave blank in quotes for the default = true
# to turn off, set = false (no quotes)
[events]
    link_archive = "" # default is true

# customize your site colors
# these colors get applied by layouts/partials/custom-site.css
# then, the layouts/partials/head_includes.html uses that partial
# the partial head_includes.html is called in the partial header.html everywhere!
[colors]
    text = "#404040" # off-black
    # Links
    link = "#CA225E" # main accent
    link_hover = "#cc3168" #lighter
    # Footer
    footer_primary = "#CA225E40"
    footer_text = "#CA225E" 
    # Backgrounds
    background = "#ffffff" 
    home_section_odd = "#ffffff"
    home_section_even = "#fcfcfc" 
    # Menu
    menu_primary = "#ffffff" 
    menu_text = "black"
    menu_text_active = "#CA225E"
    menu_text_current = "#CA225E"
    menu_decorate_current = "none"
    menu_title = "#CA225E" # Tidymodels
    menu_title_active = "#00000075" 
    menu_box_hover = "white" 
    menu_box_active = "#fcfcfc" 
    # Tables
    header_background = "#1a162d80"
    table_row_even = "#fcfcfc"
    table_row_odd = "#1a162d10"
